version: '3.4'

services:
  web:
    image: a3-usabilidade-web
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    env_file:
     - .env
    ports:
      - 3000:3000
    volumes:
      - .:/app
