version: '3.4'

services:
  web:
    image: wvxbs/a3-usabilidade-web:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    env_file:
     - .env
    ports:
      - 3000:3000
    volumes:
      - .:/app
    restart: on-failure

  api:
    image: wvxbs/a3-usabilidade-server:latest
    ports: 
      - 4040:4040
    volumes: 
      - .:/server
    restart: on-failure

  nginx:
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - web
    - api